[book]
authors = ["jingchen wang"]
language = "en"
multilingual = false
src = "src"
title = "cyber-doctor-series"

[output.html]
git-repository-url = "https://github.com/chanmaoganda/cyber-doctor-series"